apiVersion: v1
entries:
  dynamic-loader:
  - apiVersion: v2
    appVersion: humble
    created: "2026-03-26T14:25:43.771695+01:00"
    description: Dynamic loading ROS 2 pattern with camera service and runtime-loadable
      YOLO module via FastAPI
    digest: 4fd76146eca11b52601c6265c17f237eaa32134dfdae8163bc97e0bdc179eeda
    keywords:
    - ros2
    - fastapi
    - dynamic loading
    maintainers:
    - email: mmateo@cigip.upv.es
      name: Miguel-Angel-Mateo-Casali
    name: dynamic-loader
    type: application
    urls:
    - https://cigip-upv.github.io/Kubernetes-deployment-patterns/charts/dynamic-loader-2.0.1.tgz
    version: 2.0.1
  ros2-microservices:
  - apiVersion: v2
    appVersion: humble
    created: "2026-03-26T14:25:43.771951+01:00"
    description: Microservices ROS 2 pattern with decoupled camera and YOLO services
    digest: b720a1fc076a119e39a81c15a17d1ca4de4594052323ba2aee66b59b0f7cb35e
    keywords:
    - ros2
    - microservices
    - robotics
    maintainers:
    - email: mmateo@cigip.upv.es
      name: Miguel-Angel-Mateo-Casali
    name: ros2-microservices
    type: application
    urls:
    - https://cigip-upv.github.io/Kubernetes-deployment-patterns/charts/ros2-microservices-2.0.1.tgz
    version: 2.0.1
  ros2-monolithic:
  - apiVersion: v2
    appVersion: humble
    created: "2026-03-26T14:25:43.772387+01:00"
    description: Monolithic ROS 2 pattern with camera + YOLO + detections in a single
      runtime container
    digest: c48c06ae290bf87ab7b473c4c497666a4375ac8036b25f0713768a24ed733d4f
    keywords:
    - ros2
    - monolithic
    - robotics
    maintainers:
    - email: mmateo@cigip.upv.es
      name: Miguel-Angel-Mateo-Casali
    name: ros2-monolithic
    type: application
    urls:
    - https://cigip-upv.github.io/Kubernetes-deployment-patterns/charts/ros2-monolithic-2.0.1.tgz
    version: 2.0.1
  ros2-overlay:
  - apiVersion: v2
    appVersion: humble
    created: "2026-03-26T14:25:43.772589+01:00"
    description: Helm chart for ROS2 overlay-workspaces pattern (base ws + overlay
      ws)
    digest: ad35a34594b2dd31a9926b7bcd7dfed141086f93dc4c63f3507c6b17412b2585
    keywords:
    - ros2
    - overlay
    - cloud-edge
    maintainers:
    - email: mmateo@cigip.upv.es
      name: Miguel-Angel-Mateo-Casali
    name: ros2-overlay
    type: application
    urls:
    - https://cigip-upv.github.io/Kubernetes-deployment-patterns/charts/ros2-overlay-1.0.1.tgz
    version: 1.0.1
generated: "2026-03-26T14:25:43.769691+01:00"
