apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamic-loader.fullname" . }}
  labels:
    {{- include "dynamic-loader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "dynamic-loader.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
