apiVersion: v2
name: dynamic-loader
description: Dynamic loading ROS 2 pattern with camera service and runtime-loadable YOLO module via FastAPI
type: application
version: 2.0.0
appVersion: humble
keywords:
  - ros2
  - fastapi
  - dynamic loading
maintainers:
  - name: Miguel-Angel-Mateo-Casali
    email: mmateo@cigip.upv.es
