{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros2-monolithic.fullname" . }}
  labels:
    {{- include "ros2-monolithic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ros2-monolithic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: diagnostics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
{{- end }}
