{{- if .Values.llava.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros2-microservices.fullname" . }}-llava-peers
  labels:
    {{- include "ros2-microservices.labels" . | nindent 4 }}
    component: llava
spec:
  clusterIP: None
  selector:
    app: llava
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dds
      port: 7400
      protocol: UDP
{{- end }}
