apiVersion: v2
name: ros2-monolithic
description: Monolithic ROS 2 pattern with camera + YOLO + detections in a single runtime container
type: application
version: 2.0.0
appVersion: humble
keywords:
  - ros2
  - monolithic
  - robotics
maintainers:
  - name: Miguel-Angel-Mateo-Casali
    email: mmateo@cigip.upv.es
